charon:
  ~chart: app
  image: lsagetlethias/charon:latest
  probesPath: /healthz
  host: "{{ .Values.global.host }}"
  envFrom:
    - secretRef:
        name: "charon"
    - configMapRef:
        name: "charon-config"
  vars:
    CHARON_PUBLIC_HOST: "https://charon-{{ .Values.global.host }}"
    DEBUG: "charon:*"
    CHARON_PORT: "3000"
